#!/usr/bin/env bash
# Regenerate tests/fixtures/perft_canonical6.txt and
# tests/fixtures/perft_whittington.epd by querying Stockfish for perft counts.
#
# Per ADR-0006 (`docs/decisions/0006-stockfish-as-perft-oracle.md`), Stockfish
# is the sole external oracle for perft data. This script:
#   1. Generates D1–D6 totals for the canonical six positions.
#   2. Generates D1–D4 totals for every FEN in the Whittington corpus
#      (downloaded fresh from the public ChrisWhittington/Chess-EPDs repo).
#
# Idempotent: run from repo root, regenerates both fixtures.
# Run via: ./scripts/regen-perft-fixtures.sh

set -euo pipefail

# -------------------------------------------------------------------------
# Preconditions.
# -------------------------------------------------------------------------

if ! command -v stockfish >/dev/null 2>&1; then
    echo "ERROR: stockfish not on PATH; install via 'brew install stockfish'" >&2
    exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIX_DIR="$REPO_ROOT/tests/fixtures"
mkdir -p "$FIX_DIR"

SF_VERSION="$(echo 'uci' | stockfish 2>/dev/null | awk '/^id name/ { sub(/^id name /, ""); print; exit }')"
DATE="$(date +%Y-%m-%d)"

echo "Stockfish version: $SF_VERSION"
echo "Generation date:   $DATE"

# -------------------------------------------------------------------------
# perft_for_fen: prints "<fen>; D1 N; D2 N; ...; Dmax N"
# -------------------------------------------------------------------------

perft_for_fen() {
    local fen="$1"
    local max_depth="$2"
    local out="$fen"
    local d
    for ((d = 1; d <= max_depth; d++)); do
        local n
        n=$(
            {
                echo "position fen $fen"
                echo "go perft $d"
                echo "quit"
            } | stockfish 2>/dev/null \
                | awk '/^Nodes searched:/ { print $3; exit }'
        )
        if [[ -z "$n" ]]; then
            echo "ERROR: stockfish produced no 'Nodes searched' line for $fen at depth $d" >&2
            exit 1
        fi
        out+="; D$d $n"
    done
    echo "$out"
}

# -------------------------------------------------------------------------
# Canonical six.
# -------------------------------------------------------------------------

CANONICAL_OUT="$FIX_DIR/perft_canonical6.txt"
CANONICAL_FENS=(
    "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
    "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1"
    "8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1"
    "r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1"
    "rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8"
    "r4rk1/1pp1qppp/p1np1n2/2b1p1B1/2B1P1b1/P1NP1N2/1PP1QPPP/R4RK1 w - - 0 10"
)

echo "==> Generating canonical-6 fixture (D1-D6 each)"
{
    echo "# Canonical six perft positions, depths 1-6."
    echo "# Generator: $SF_VERSION (Homebrew)."
    echo "# Generated:  $DATE."
    echo "# Format: <FEN>; D1 N; D2 N; D3 N; D4 N; D5 N; D6 N"
    echo "# D0 is implicit (1).  See docs/decisions/0006-stockfish-as-perft-oracle.md."
    echo "#"
    echo "# Position 1 (Initial), 2 (Kiwipete), 3, 4, 5, 6 — the standard CPW set."
    for fen in "${CANONICAL_FENS[@]}"; do
        echo "Processing: $fen" >&2
        perft_for_fen "$fen" 6
    done
} >"$CANONICAL_OUT"

echo "==> Wrote $CANONICAL_OUT"

# -------------------------------------------------------------------------
# Whittington corpus.
# Source: https://github.com/ChrisWhittington/Chess-EPDs/blob/master/perft.epd
# Per ADR-0006, we use the FEN list only and regenerate the counts.
# -------------------------------------------------------------------------

WHITTINGTON_URL="https://raw.githubusercontent.com/ChrisWhittington/Chess-EPDs/master/perft.epd"
WHITTINGTON_OUT="$FIX_DIR/perft_whittington.epd"
TMP=$(mktemp "${TMPDIR:-/tmp}/perft_whittington.XXXXXX")
trap 'rm -f "$TMP"' EXIT

echo "==> Downloading Whittington FEN list from $WHITTINGTON_URL"
curl -sSfL "$WHITTINGTON_URL" -o "$TMP"
# `set -e` + `pipefail` make `||` of a successful pipeline a no-op, so a
# clean curl-then-awk sets COMMIT_HASH to just the hash. We pre-compute
# both branches separately to avoid the prior-iteration "<hash>\nunknown"
# stacking bug when curl warned non-fatally.
COMMIT_HASH="$( { curl -sSfL https://api.github.com/repos/ChrisWhittington/Chess-EPDs/commits/master 2>/dev/null \
    | awk -F'"' '/^  "sha":/ { print $4; exit }'; } || true )"
COMMIT_HASH="${COMMIT_HASH:-unknown}"

echo "==> Generating Whittington fixture (D1-D4 each, $(grep -c '^[^#]' "$TMP" || echo "?") positions)"
{
    echo "# Whittington perft regression suite (D1-D4)."
    echo "# Position list: ChrisWhittington/Chess-EPDs/perft.epd"
    echo "# Upstream commit: $COMMIT_HASH"
    echo "# Counts regenerated by: $SF_VERSION (Homebrew)."
    echo "# Generated: $DATE."
    echo "#"
    echo "# Per ADR-0006 we use only the FEN list as a diversity corpus and regenerate"
    echo "# our own counts. Upstream-published counts are not consumed."
    echo "# Format: <FEN>; D1 N; D2 N; D3 N; D4 N"
    echo "#"
    while IFS= read -r line; do
        # Skip blank lines and comments.
        [[ -z "${line// }" ]] && continue
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        # Extract the FEN (everything before the first ';').
        local_fen="${line%%;*}"
        local_fen="${local_fen%"${local_fen##*[![:space:]]}"}" # rtrim
        local_fen="${local_fen#"${local_fen%%[![:space:]]*}"}" # ltrim
        if [[ -z "$local_fen" ]]; then
            continue
        fi
        echo "Processing: $local_fen" >&2
        perft_for_fen "$local_fen" 4
    done <"$TMP"
} >"$WHITTINGTON_OUT"

echo "==> Wrote $WHITTINGTON_OUT"
echo "Done."
